# Generated by Django 5.2.8 on 2025-12-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0002_alter_customuser_phone_number_adminactivitylog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("max_retries", models.IntegerField(default=3)),
                ("retry_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "created_at"],
                        name="firstApp_ph_phone_n_a9e5a6_idx",
                    )
                ],
            },
        ),
    ]
