# Generated by Django 5.2.8 on 2025-12-02 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0003_phoneotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                (
                    "city",
                    models.CharField(
                        choices=[("Indore", "Indore")], default="Indore", max_length=50
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("Fridge Repair", "Fridge Repair"),
                            ("Washing Machine Repair", "Washing Machine Repair"),
                            ("Geyser Repair", "Geyser Repair"),
                            (
                                "Electrical Wiring / Short Circuit",
                                "Electrical Wiring / Short Circuit",
                            ),
                            ("Fan / Motor Repair", "Fan / Motor Repair"),
                            ("LED / Tube Light Repair", "LED / Tube Light Repair"),
                            ("Other Appliance Repair", "Other Appliance Repair"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("problem_description", models.TextField()),
                (
                    "visiting_charge",
                    models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
                ),
                (
                    "extra_charge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
