# Generated by Django 5.2.8 on 2025-12-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0004_product_purchase_price_product_vendor_purchaseentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="free_delivery_used_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_orders_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="is_trending",
            field=models.BooleanField(
                default=False, help_text="Mark this product as trending"
            ),
        ),
    ]
