# Generated by Django 5.2.8 on 2025-12-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0005_customuser_free_delivery_used_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Publicly displayed name",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("STAFF", "Staff"), ("USER", "User")],
                default="USER",
                max_length=50,
            ),
        ),
    ]
