# Generated by Django 5.2.8 on 2025-12-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0005_emailotp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhoneOTP",
        ),
    ]
