# Generated by Django 5.2.8 on 2025-12-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0006_customuser_display_name_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_charge_status",
            field=models.CharField(
                choices=[("ESTIMATED", "Estimated"), ("CONFIRMED", "Confirmed")],
                default="ESTIMATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="free_delivery_applied",
            field=models.BooleanField(
                default=False,
                help_text="Whether free delivery was applied to this order",
            ),
        ),
    ]
