# Generated by Django 5.2.8 on 2025-12-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0007_customuser_is_email_verified_customuser_pincode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="area",
            field=models.CharField(
                choices=[
                    ("Vijay Nagar", "Vijay Nagar"),
                    ("Sukhliya", "Sukhliya"),
                    ("Abhinandan Nagar", "Abhinandan Nagar"),
                    ("Palasia", "Palasia"),
                    ("Rajendra Nagar", "Rajendra Nagar"),
                    ("Nipania", "Nipania"),
                    ("Bhawarkua", "Bhawarkua"),
                    ("Other", "Other region"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
