# Generated by Django 5.2.8 on 2025-12-15 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0007_order_delivery_charge_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="firstApp.order",
            ),
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("ORDER_STATUS", "Order Status Update"),
                            ("ORDER_RECEIPT", "Order Receipt"),
                            ("DELIVERY_OTP", "Delivery OTP"),
                            ("ORDER_DELIVERED", "Order Delivered"),
                            ("APPOINTMENT_STATUS", "Appointment Status Update"),
                            ("APPOINTMENT_COMPLETE", "Appointment Complete"),
                            ("OTP_VERIFICATION", "OTP Verification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("RETRY", "Retry"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="firstApp.appointment",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="firstApp.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="firstApp_em_status_fa2834_idx",
                    ),
                    models.Index(
                        fields=["email_type", "recipient"],
                        name="firstApp_em_email_t_d226d1_idx",
                    ),
                ],
            },
        ),
    ]
