# Generated by Django 5.2.8 on 2025-12-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0008_appointment_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
