# Generated by Django 5.2.8 on 2025-12-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0008_review_is_approved_review_order_emaillog"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional: Upload a photo of the product",
                null=True,
                upload_to="review_images/",
            ),
        ),
    ]
