# Generated by Django 5.2.8 on 2025-12-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0009_review_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
