# Generated by Django 5.2.8 on 2025-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0009_appointment_cancellation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="address_line1",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="appointment",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="house_number",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="appointment",
            name="landmark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="pincode",
            field=models.CharField(default="452001", max_length=6),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
