# Generated by Django 5.2.8 on 2025-12-16 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0010_alter_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('AUTO_REVENUE_UPDATE', 'Attempted Auto Revenue Update'), ('AUTO_SALES_UPDATE', 'Attempted Auto Sales Update'), ('ORDER_TO_FINANCE', 'Order Data Used in Finance Calculation'), ('OTHER', 'Other Violation')], max_length=30)),
                ('description', models.TextField(help_text='Details of the attempted violation')),
                ('source_module', models.CharField(help_text='Module/function that attempted the update', max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstApp.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Validation Log',
                'verbose_name_plural': 'Financial Validation Logs',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['violation_type', 'detected_at'], name='firstApp_fi_violati_11c1d3_idx')],
            },
        ),
    ]
