# Generated by Django 5.2.8 on 2025-12-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0011_alter_appointment_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("CCTV Installation", "CCTV Installation"),
                    (
                        "Electrical Wiring / Short Circuit",
                        "Electrical Wiring / Short Circuit",
                    ),
                    ("Fan / Motor Repair", "Fan / Motor Repair"),
                    ("Fridge Repair", "Fridge Repair"),
                    ("Geyser Repair", "Geyser Repair"),
                    ("LED / Tube Light Repair", "LED / Tube Light Repair"),
                    ("Underground Wiring", "Underground Wiring"),
                    ("Washing Machine Repair", "Washing Machine Repair"),
                    ("Other Appliance Repair", "Other Appliance Repair"),
                ],
                max_length=100,
            ),
        ),
    ]
