# Generated by Django 5.2.8 on 2025-12-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0011_financialvalidationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='delivery_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Delivery charges collected (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='labor_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Labor charges for the day (optional)', max_digits=10, null=True),
        ),
    ]
