# Generated by Django 5.2.8 on 2025-12-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0012_add_labor_delivery_charges'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyexpenditure',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_daily_expense_date'),
        ),
        migrations.AddConstraint(
            model_name='dailysales',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_daily_sales_date'),
        ),
    ]
