# Generated by Django 5.2.8 on 2025-12-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0012_alter_appointment_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address_line1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="house_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="landmark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
