# Generated by Django 5.2.8 on 2025-12-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0013_enforce_unique_daily_entries'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyexpenditure',
            name='unique_daily_expense_date',
        ),
        migrations.AddConstraint(
            model_name='dailyexpenditure',
            constraint=models.UniqueConstraint(fields=('date', 'payment_method'), name='unique_daily_expense_date_payment'),
        ),
    ]
