# Generated by Django 5.2.8 on 2025-12-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0013_customuser_address_line1_customuser_address_line2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address_line2",
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True, default="Indore", max_length=100, null=True
            ),
        ),
    ]
