# Generated by Django 5.2.8 on 2025-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0014_update_expense_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyexpenditure',
            name='unique_daily_expense_date_payment',
        ),
        migrations.RemoveField(
            model_name='dailyexpenditure',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='dailyexpenditure',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='dailyexpenditure',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Cash expenses for the day', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyexpenditure',
            name='online_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Online expenses for the day', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyexpenditure',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-calculated total (Online + Cash)', max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='dailyexpenditure',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_daily_expenditure_date'),
        ),
    ]
