# Generated by Django 5.2.8 on 2025-12-07 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0015_order_delivery_charge_order_delivery_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member assigned to deliver this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
