# Generated by Django 5.2.8 on 2025-12-18 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0017_emaillogintoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("buyer_name", models.CharField(max_length=200)),
                (
                    "buyer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional - links receipt to user account",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("buyer_phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "buyer_address",
                    models.TextField(
                        blank=True, help_text="No house number required", null=True
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(default="Shiv Shakti Electrical", max_length=200),
                ),
                ("shop_address", models.TextField(default="Indore, Madhya Pradesh")),
                (
                    "shop_phone",
                    models.CharField(default="+91 9993149226", max_length=15),
                ),
                ("shop_gst", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="GST/Tax", max_digits=10
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("grand_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "qr_code_data",
                    models.TextField(
                        blank=True, help_text="Data encoded in QR code", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for admin", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin who created this receipt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Receipt",
                "verbose_name_plural": "Offline Receipts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="firstApp.offlinereceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receipt Item",
                "verbose_name_plural": "Receipt Items",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="offlinereceipt",
            index=models.Index(
                fields=["receipt_number"], name="firstApp_of_receipt_d8e81d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinereceipt",
            index=models.Index(
                fields=["buyer_email"], name="firstApp_of_buyer_e_b08753_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinereceipt",
            index=models.Index(
                fields=["-created_at"], name="firstApp_of_created_77cb54_idx"
            ),
        ),
    ]
