# Generated by Django 5.2.8 on 2025-12-18 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0018_offlinereceipt_receiptitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offlinereceipt",
            name="corrected_by_receipt",
            field=models.ForeignKey(
                blank=True,
                help_text="Corrected receipt reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrected_from",
                to="firstApp.offlinereceipt",
            ),
        ),
        migrations.AddField(
            model_name="offlinereceipt",
            name="financial_year",
            field=models.CharField(
                default="2024-25",
                editable=False,
                help_text="e.g., 2024-25",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offlinereceipt",
            name="original_receipt",
            field=models.ForeignKey(
                blank=True,
                help_text="Original receipt if this is a correction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrections",
                to="firstApp.offlinereceipt",
            ),
        ),
        migrations.AddField(
            model_name="offlinereceipt",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="receipt_pdfs/"),
        ),
        migrations.AddField(
            model_name="offlinereceipt",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offlinereceipt",
            name="qr_code_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="receipt_qrcodes/"
            ),
        ),
        migrations.AddField(
            model_name="offlinereceipt",
            name="sequence_number",
            field=models.IntegerField(
                default=1, editable=False, help_text="Sequential number within FY"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offlinereceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("VOID", "Void"),
                    ("CORRECTED", "Corrected"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="offlinereceipt",
            name="void_reason",
            field=models.TextField(
                blank=True, help_text="Reason for voiding receipt", null=True
            ),
        ),
        migrations.AddField(
            model_name="offlinereceipt",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offlinereceipt",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who voided this receipt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voided_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="offlinereceipt",
            name="qr_code_data",
            field=models.TextField(
                blank=True, help_text="Data encoded in receipt QR code", null=True
            ),
        ),
        migrations.AlterField(
            model_name="offlinereceipt",
            name="receipt_number",
            field=models.CharField(
                db_index=True, editable=False, max_length=50, unique=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="offlinereceipt",
            unique_together={("financial_year", "sequence_number")},
        ),
        migrations.AddIndex(
            model_name="offlinereceipt",
            index=models.Index(
                fields=["financial_year", "sequence_number"],
                name="firstApp_of_financi_82bfcc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offlinereceipt",
            index=models.Index(fields=["status"], name="firstApp_of_status_37971c_idx"),
        ),
    ]
