# Generated by Django 5.2.8 on 2025-12-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0019_offlinereceipt_corrected_by_receipt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="financial_year",
            field=models.CharField(
                blank=True, help_text="e.g., 2024-25", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="order_qrcodes/"),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_qr_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_sequence",
            field=models.IntegerField(
                blank=True, help_text="Sequential number within FY", null=True
            ),
        ),
    ]
