# Generated by Django 5.2.8 on 2025-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0020_order_financial_year_order_receipt_generated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total discount applied (calculated from MRP - Unit Price)",
                max_digits=10,
                verbose_name="Discount Amount",
            ),
        ),
        migrations.AddField(
            model_name="receiptitem",
            name="mrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original MRP of the product",
                max_digits=10,
                null=True,
                verbose_name="MRP (Maximum Retail Price)",
            ),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Final selling price per unit after discount",
                max_digits=10,
                verbose_name="Selling Price",
            ),
        ),
    ]
