# Generated by Django 5.2.8 on 2025-12-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0021_receiptitem_discount_receiptitem_mrp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptitem",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Total discount applied (calculated from MRP - Unit Price)",
                max_digits=10,
                null=True,
                verbose_name="Discount Amount",
            ),
        ),
    ]
