# Generated by Django 5.2.8 on 2025-12-19 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0022_alter_receiptitem_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offlinereceipt",
            name="shop_address",
            field=models.TextField(default="B-155,Abhinandan Nagar,Indore, MP"),
        ),
        migrations.CreateModel(
            name="LoginPopup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "popup_type",
                    models.CharField(
                        choices=[
                            ("CENTER_MODAL", "Center Modal (Testing Notice)"),
                            ("BOTTOM_RIGHT", "Bottom Right Card (Offers)"),
                        ],
                        help_text="Type of popup - each type can only have one active instance",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Popup title", max_length=200)),
                (
                    "message",
                    models.TextField(help_text="Popup message content (supports HTML)"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this popup"
                    ),
                ),
                (
                    "auto_hide_seconds",
                    models.IntegerField(
                        default=0,
                        help_text="Auto-hide after X seconds (0 = manual close only)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_popups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Popup",
                "verbose_name_plural": "Login Popups",
                "ordering": ["popup_type"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Notification title/heading", max_length=200
                    ),
                ),
                ("message", models.TextField(help_text="Notification message content")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional notification image",
                        null=True,
                        upload_to="notification_images/",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All Users"),
                            ("LOCATION", "By Location"),
                            ("AREA", "By Area"),
                            ("INDIVIDUAL", "Individual User"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                (
                    "target_city",
                    models.CharField(
                        blank=True,
                        help_text="Target specific city",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "target_area",
                    models.CharField(
                        blank=True,
                        help_text="Target specific area",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this notification is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific users to target (for INDIVIDUAL type)",
                        related_name="targeted_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notifications",
                        to="firstApp.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification",
                "verbose_name_plural": "User Notifications",
                "ordering": ["-created_at"],
                "unique_together": {("user", "notification")},
            },
        ),
    ]
