# Generated by Django 5.2.8 on 2025-12-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0023_alter_offlinereceipt_shop_address_loginpopup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Brief summary for product cards (max 200 chars)",
                max_length=200,
            ),
        ),
    ]
