# Generated by Django 5.2.8 on 2025-12-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0024_product_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginpopup",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("ALL", "All Visitors (Logged in + Not logged in)"),
                    ("LOGGED_IN_ONLY", "Logged In Users Only"),
                ],
                default="LOGGED_IN_ONLY",
                help_text="Choose who should see this popup",
                max_length=20,
            ),
        ),
    ]
