# Generated by Django 5.2.8 on 2025-12-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0025_loginpopup_target_audience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
