# Generated by Django 5.2.8 on 2025-12-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0026_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
