# Generated by Django 5.2.8 on 2025-12-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0027_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
