# Generated by Django 5.2.8 on 2025-12-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0028_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoginPopup",
        ),
    ]
