# Generated by Django 5.2.8 on 2025-12-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0029_delete_loginpopup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("CCTV Installation", "CCTV Installation"),
                    (
                        "Electrical Wiring / Short Circuit",
                        "Electrical Wiring / Short Circuit",
                    ),
                    ("Fan / Motor Repair", "Fan / Motor Repair"),
                    ("Fridge Repair", "Fridge Repair"),
                    ("Geyser Repair", "Geyser Repair"),
                    ("Underground Wiring", "Underground Wiring"),
                    ("Washing Machine Repair", "Washing Machine Repair"),
                    ("Other Appliance Repair", "Other Appliance Repair"),
                    ("Geyser Installation", "Geyser Installation"),
                    ("TV Installation", "TV Installation"),
                    ("AC Installation", "AC Installation"),
                    ("Fan Installation", "Fan Installation"),
                    ("Cooler Repair", "Cooler Repair"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="ServicePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("CCTV Installation", "CCTV Installation"),
                            (
                                "Electrical Wiring / Short Circuit",
                                "Electrical Wiring / Short Circuit",
                            ),
                            ("Fan / Motor Repair", "Fan / Motor Repair"),
                            ("Fridge Repair", "Fridge Repair"),
                            ("Geyser Repair", "Geyser Repair"),
                            ("LED / Tube Light Repair", "LED / Tube Light Repair"),
                            ("Underground Wiring", "Underground Wiring"),
                            ("Washing Machine Repair", "Washing Machine Repair"),
                            ("Other Appliance Repair", "Other Appliance Repair"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("CENTRAL", "Central Indore (Rajwada, Juni Indore, etc.)"),
                            ("EAST", "East Indore (Pardesipura, Gumasta Nagar, etc.)"),
                            (
                                "WEST",
                                "West/Northwest Indore (Vijay Nagar, Nipania, etc.)",
                            ),
                            ("NORTH", "North Indore (Patnipura, Hawa Bangla, etc.)"),
                            (
                                "SOUTH",
                                "South Indore (Rajendra Nagar, Kanadia Road, etc.)",
                            ),
                            (
                                "RESIDENTIAL",
                                "Residential Colonies (Sukhliya, LIG, etc.)",
                            ),
                            ("OTHER", "Other Areas"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=200.0,
                        help_text="Base visiting/inspection charge",
                        max_digits=10,
                    ),
                ),
                (
                    "min_service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=300.0,
                        help_text="Minimum service charge (excluding parts)",
                        max_digits=10,
                    ),
                ),
                (
                    "max_service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=1500.0,
                        help_text="Maximum typical service charge",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Price",
                "verbose_name_plural": "Service Prices",
                "ordering": ["service_type", "zone"],
                "unique_together": {("service_type", "zone")},
            },
        ),
    ]
