# Generated by Django 5.2.8 on 2025-12-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0030_alter_appointment_service_type_serviceprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(max_length=100, unique=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("CENTRAL", "Central Indore"),
                            ("EAST", "East Indore"),
                            ("WEST", "West Indore"),
                            ("NORTH", "North Indore"),
                            ("SOUTH", "South Indore"),
                            ("RESIDENTIAL", "Residential Colonies"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Area Region",
                "verbose_name_plural": "Area Regions",
                "ordering": ["region", "area_name"],
            },
        ),
        migrations.CreateModel(
            name="DistanceZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("VERY_NEAR", "Very Near (0-500m)"),
                            ("NEAR", "Near (0-3 KM)"),
                            ("MEDIUM", "Medium (3-5 KM)"),
                            ("FAR", "Far (5-7 KM)"),
                            ("VERY_FAR", "Very Far (7+ KM)"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "min_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum distance in KM",
                        max_digits=5,
                    ),
                ),
                (
                    "max_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum distance in KM (use 999 for unlimited)",
                        max_digits=5,
                    ),
                ),
                (
                    "base_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=200.0,
                        help_text="Base visiting/inspection charge for this distance",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_confirmation",
                    models.BooleanField(
                        default=False,
                        help_text="If true, staff will confirm pricing manually",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Notes shown to user (e.g., 'Contact for quote')",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Distance Zone",
                "verbose_name_plural": "Distance Zones",
                "ordering": ["min_distance_km"],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="fa-tools",
                        help_text="Font Awesome icon class",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in dropdown (lower = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Type",
                "verbose_name_plural": "Service Types",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("AC Installation", "AC Installation"),
                    ("CCTV Installation", "CCTV Installation"),
                    ("Cooler Repair", "Cooler Repair"),
                    (
                        "Electrical Wiring / Short Circuit",
                        "Electrical Wiring / Short Circuit",
                    ),
                    ("Fan / Motor Repair", "Fan / Motor Repair"),
                    ("Fan Installation", "Fan Installation"),
                    ("Fridge Repair", "Fridge Repair"),
                    ("Geyser Installation", "Geyser Installation"),
                    ("Geyser Repair", "Geyser Repair"),
                    ("LED / Tube Light Repair", "LED / Tube Light Repair"),
                    ("TV Installation", "TV Installation"),
                    ("Underground Wiring", "Underground Wiring"),
                    ("Washing Machine Repair", "Washing Machine Repair"),
                    ("Other Appliance Repair", "Other Appliance Repair"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="serviceprice",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("AC Installation", "AC Installation"),
                    ("CCTV Installation", "CCTV Installation"),
                    ("Cooler Repair", "Cooler Repair"),
                    (
                        "Electrical Wiring / Short Circuit",
                        "Electrical Wiring / Short Circuit",
                    ),
                    ("Fan / Motor Repair", "Fan / Motor Repair"),
                    ("Fan Installation", "Fan Installation"),
                    ("Fridge Repair", "Fridge Repair"),
                    ("Geyser Installation", "Geyser Installation"),
                    ("Geyser Repair", "Geyser Repair"),
                    ("LED / Tube Light Repair", "LED / Tube Light Repair"),
                    ("TV Installation", "TV Installation"),
                    ("Underground Wiring", "Underground Wiring"),
                    ("Washing Machine Repair", "Washing Machine Repair"),
                    ("Other Appliance Repair", "Other Appliance Repair"),
                ],
                max_length=100,
            ),
        ),
    ]
