# Generated by Django 5.2.8 on 2025-12-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0031_arearegion_distancezone_servicetype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="charge_within_1km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Charge for within 1 KM (optional)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="charge_within_3km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Charge for within 3 KM (optional)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="charge_within_500m",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Charge for within 500 meters (optional)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="charge_within_5km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Charge for within 5 KM (optional)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="charge_within_7km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Charge for within 7 KM (optional)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="default_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=300.0,
                help_text="Fallback/default charge if distance not matched",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Price (Auto-applied)"),
                    ("confirm", "Confirm Later (Admin will confirm)"),
                ],
                default="fixed",
                help_text="Fixed: Show price. Confirm: Admin confirms price after booking.",
                max_length=20,
            ),
        ),
    ]
