# Generated by Django 5.2.8 on 2025-12-20 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0032_servicetype_charge_within_1km_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Distance from shop in KM",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="pricing_confirmed",
            field=models.BooleanField(
                default=False, help_text="True if price is confirmed by admin"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected service from admin-managed list",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="firstApp.servicetype",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC Installation", "AC Installation"),
                    ("CCTV Installation", "CCTV Installation"),
                    ("Cooler Repair", "Cooler Repair"),
                    (
                        "Electrical Wiring / Short Circuit",
                        "Electrical Wiring / Short Circuit",
                    ),
                    ("Fan / Motor Repair", "Fan / Motor Repair"),
                    ("Fan Installation", "Fan Installation"),
                    ("Fridge Repair", "Fridge Repair"),
                    ("Geyser Installation", "Geyser Installation"),
                    ("Geyser Repair", "Geyser Repair"),
                    ("LED / Tube Light Repair", "LED / Tube Light Repair"),
                    ("TV Installation", "TV Installation"),
                    ("Underground Wiring", "Underground Wiring"),
                    ("Washing Machine Repair", "Washing Machine Repair"),
                    ("Other Appliance Repair", "Other Appliance Repair"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
