# Generated by Django 5.2.8 on 2025-12-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0033_appointment_distance_km_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("ONLINE_DELIVERY", "Online (Pay at Delivery using QR code)"),
                ],
                default="COD",
                max_length=20,
            ),
        ),
    ]
