# Generated by Django 5.2.8 on 2025-12-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0034_add_online_payment_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("enquiry", "Enquiry-Based Order"),
                    ("direct", "Direct Order (Legacy)"),
                ],
                default="enquiry",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pricing_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="True when admin has entered and confirmed pricing",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="user_notes",
            field=models.TextField(
                blank=True,
                help_text="Special requirements or notes from user",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Enquiry", "Pending Enquiry"),
                    ("Price Shared", "Price Shared"),
                    ("Confirmed", "Confirmed"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending Enquiry",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Admin-entered product price (hidden until confirmed)",
                max_digits=10,
            ),
        ),
    ]
