# Generated by Django 5.2.8 on 2025-12-21 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0035_order_order_type_order_pricing_confirmed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "message",
                    models.TextField(
                        help_text="Main announcement message. HTML allowed."
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("center", "Center Modal"),
                            ("bottom_right", "Bottom Right Toast"),
                            ("both", "Both Positions"),
                        ],
                        default="bottom_right",
                        max_length=20,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("info", "Info (Blue)"),
                            ("success", "Success (Green)"),
                            ("warning", "Warning (Yellow)"),
                            ("danger", "Danger (Red)"),
                            ("primary", "Primary (Brand)"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Visitors"),
                            ("logged_in", "Logged In Users Only"),
                            ("guests", "Guests Only"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_dismissible",
                    models.BooleanField(
                        default=True, help_text="Can users dismiss this announcement?"
                    ),
                ),
                (
                    "show_once_per_session",
                    models.BooleanField(
                        default=True, help_text="Only show once per browser session"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        help_text="Optional action button text",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "button_url",
                    models.URLField(
                        blank=True, help_text="URL for the action button", null=True
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to start showing (leave blank for immediately)",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to stop showing (leave blank for indefinitely)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Announcement",
                "verbose_name_plural": "Site Announcements",
                "ordering": ["-created_at"],
            },
        ),
    ]
