# Generated by Django 5.2.8 on 2025-12-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0036_siteannouncement"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfillment_type",
            field=models.CharField(
                choices=[
                    ("PICKUP", "Pick from Store"),
                    ("DELIVERY", "Online Delivery"),
                ],
                default="DELIVERY",
                help_text="How customer will receive the order",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Enquiry", "Pending Enquiry"),
                    ("Price Shared", "Price Shared"),
                    ("Confirmed", "Confirmed"),
                    ("Ready for Pickup", "Ready for Pickup"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending Enquiry",
                max_length=20,
            ),
        ),
    ]
