# Generated by Django 5.2.8 on 2025-12-22 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0037_add_fulfillment_type_to_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Electrician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="electrician_pics/"
                    ),
                ),
                (
                    "specializations",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of specializations"
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, help_text="Years of experience"
                    ),
                ),
                (
                    "show_on_home_page",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, electrician will be visible on home page under 'Our Electricians'",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this electrician currently available",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this electrician",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Electrician",
                "verbose_name_plural": "Electricians",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes for admin (not visible to customer)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="is_admin_booked",
            field=models.BooleanField(
                default=False,
                help_text="True if appointment was booked by admin on behalf of customer",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_visible_on_website",
            field=models.BooleanField(
                default=False,
                help_text="Show this product on the website (default: hidden)",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("In Progress", "In Progress"),
                    ("Approved", "Approved"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="assigned_electrician",
            field=models.ForeignKey(
                blank=True,
                help_text="Electrician assigned to this appointment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="firstApp.electrician",
            ),
        ),
        migrations.CreateModel(
            name="Warranty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(max_length=20)),
                ("customer_email", models.EmailField(max_length=254)),
                ("product_name", models.CharField(max_length=200)),
                (
                    "product_serial",
                    models.CharField(
                        blank=True,
                        help_text="Product serial number or identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "product_brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="warranty_products/"
                    ),
                ),
                ("purchase_date", models.DateField()),
                (
                    "warranty_duration",
                    models.PositiveIntegerField(
                        default=12, help_text="Warranty duration value"
                    ),
                ),
                (
                    "warranty_unit",
                    models.CharField(
                        choices=[("MONTHS", "Months"), ("YEARS", "Years")],
                        default="MONTHS",
                        max_length=10,
                    ),
                ),
                (
                    "warranty_expiry_date",
                    models.DateField(
                        blank=True, help_text="Auto-calculated on save", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("VOIDED", "Voided"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "void_reason",
                    models.TextField(
                        blank=True, help_text="Reason if warranty was voided", null=True
                    ),
                ),
                (
                    "purchase_invoice",
                    models.CharField(
                        blank=True,
                        help_text="Invoice/Bill number",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_warranties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to user account if exists",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warranties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Warranty",
                "verbose_name_plural": "Warranties",
                "ordering": ["-purchase_date"],
                "indexes": [
                    models.Index(
                        fields=["customer_email", "status"],
                        name="firstApp_wa_custome_59f8e7_idx",
                    ),
                    models.Index(
                        fields=["warranty_expiry_date", "status"],
                        name="firstApp_wa_warrant_cc9fa0_idx",
                    ),
                ],
            },
        ),
    ]
