# Generated by Django 5.2.8 on 2025-12-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0038_add_electrician_warranty_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_indore",
            field=models.BooleanField(
                default=True, help_text="True if location is verified as Indore"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="location_verification",
            field=models.CharField(
                choices=[
                    ("GPS confirmed", "GPS confirmed"),
                    ("Manual entry", "Manual entry"),
                ],
                default="Manual entry",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="price_calculation",
            field=models.CharField(
                choices=[
                    ("Auto-calculated", "Auto-calculated"),
                    ("Pending confirmation", "Pending confirmation"),
                ],
                default="Pending confirmation",
                max_length=50,
            ),
        ),
    ]
